# Generated by Django 3.0.5 on 2020-04-16 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 21, 49, 16, 942256), verbose_name='date published'),
        ),
    ]
